### ISSUE TITLE
Add Basic Tech

### ISSUE THREAD

**Issue by Rod995** [Rod995/Battletech#1]
We'll need one *basic armor* and at least 4 different *weapons* for the starter mod.
Problem is, you haven't even started @Rod995!

**Comment by Rod995** [comment]
Still no armor, but there's 4 guns.
You're almost done.

**Comment by Rod995** [comment]
Jesus Christ!
Finish this!

**Comment by Rod995** [comment]
I think you could either go with regular armor, or vehicles.

**Comment by Rod995** [comment]
There's an armor beta now, that barely works.
*Barely.*

**Comment by Rod995** [comment]
This https://github.com/CleverRaven/Cataclysm-DDA/issues/26860
Should help fix it and stuff.
https://github.com/CleverRaven/Cataclysm-DDA/issues/26836
This should be a *major* advantage.

**Comment by hyper2snyper** [comment]
Why are you talking to yourself?

**Comment by Rod995** [comment]
Leaving notes regarding my thought processes.

**Comment by Rod995** [comment]
Tis actually done.
Huh.
