### ISSUE TITLE
Hub Assemblies needed. Nonexistent steereable_wheels cause errors on load.

### ISSUE THREAD

**Issue by TheRafters** [Rod995/Battletech#10]
**Describe the bug**
Steerable Wheels don't exist anymore. New system requires steerable/non-steerable hub assemblies and standard wheels. The game gets angry upon loading.

**To Reproduce**
Load the game on newest experimental, complaints ensue.

**Additional context**
I've fixed this twice locally and overwritten my fixes twice now...Please save me from myself.

**Comment by Rod995** [comment]
Currently working on using the new `"parts":` thingie to help with organization.
Hub Assemblies will also be addressed with that PR.

**Comment by Rod995** [comment]
All done, I do believe.

**Comment by Rod995** [comment]
Wait, I should double-check that everything is fine, before I close the thingie.

**Comment by Rod995** [comment]
Packrat is done, but the two test vehicles need to be fixed as well.

**Comment by Rod995** [comment]
Those *five* other test vehicles have been fixed.
`AC/2`
`RAC/2`
`AC/5`
`AC/10`
And the glorious `AC/20`.
However, it's on the engine refactoring branch.
